-- Esquema SQL para la base de datos de Alivio en Supabase
-- Puedes ejecutar esto directamente en el SQL Editor de tu proyecto de Supabase.
-- Es idempotente: se puede volver a correr sobre una base ya creada.

-- Crear el esquema personalizado "alivio" si no existe
CREATE SCHEMA IF NOT EXISTS alivio;

-- ─────────────────────────────────────────────────────────────────────────────
-- Suscripciones a notificaciones push
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS alivio.push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription JSONB NOT NULL,                -- Endpoint y llaves (auth, p256dh) del navegador. Objeto vacío en Android nativo.
  fcm_token TEXT,                             -- Token de Firebase Cloud Messaging. Solo en Android nativo.
  alert_time VARCHAR(5) NOT NULL,             -- Formato "HH:MM" de 24 horas (ej: "17:00")
  timezone_offset INT DEFAULT 0 NOT NULL,     -- Desplazamiento en minutos respecto a UTC
  message TEXT NOT NULL,                      -- Mensaje de confort personalizado generado por la IA para la tarde
  last_sent_at TIMESTAMPTZ,                   -- Último envío efectivo. Base de la deduplicación en cron-push.
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Columnas añadidas después de la creación original de la tabla
ALTER TABLE alivio.push_subscriptions ADD COLUMN IF NOT EXISTS fcm_token TEXT;
ALTER TABLE alivio.push_subscriptions ADD COLUMN IF NOT EXISTS last_sent_at TIMESTAMPTZ;

-- El cron busca por token y el alta deduplica por token: sin índice hace scan completo.
CREATE INDEX IF NOT EXISTS push_subscriptions_fcm_token_idx
  ON alivio.push_subscriptions (fcm_token)
  WHERE fcm_token IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- Permisos
-- ─────────────────────────────────────────────────────────────────────────────
-- Toda la API usa el service role. `anon` y `authenticated` no deben tener ningún
-- permiso sobre esta tabla: contiene endpoints de push y tokens FCM de los usuarios.
ALTER TABLE alivio.push_subscriptions ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA alivio TO service_role;
REVOKE ALL ON SCHEMA alivio FROM anon, authenticated;

GRANT ALL ON TABLE alivio.push_subscriptions TO service_role;
REVOKE ALL ON TABLE alivio.push_subscriptions FROM anon, authenticated;

-- Retirar las políticas heredadas que abrían la tabla al rol anónimo
DROP POLICY IF EXISTS "Permitir insertar suscripciones" ON alivio.push_subscriptions;
DROP POLICY IF EXISTS "Permitir lectura al administrador" ON alivio.push_subscriptions;

-- Sin políticas: con RLS activo y sin grants, solo el service role (que las omite)
-- puede leer o escribir. Es exactamente lo que necesita la API.
