-- Esquema SQL para la base de datos de Alivio en Supabase
-- Puedes ejecutar esto directamente en el SQL Editor de tu proyecto de Supabase.

-- Crear el esquema personalizado "alivio" si no existe
CREATE SCHEMA IF NOT EXISTS alivio;

-- Crear la tabla para almacenar las suscripciones a notificaciones push dentro del esquema alivio
CREATE TABLE IF NOT EXISTS alivio.push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription JSONB NOT NULL,                -- Contiene el endpoint y llaves (auth, p256dh) del navegador
  alert_time VARCHAR(5) NOT NULL,             -- Formato "HH:MM" de 24 horas (ej: "17:00")
  timezone_offset INT DEFAULT 0 NOT NULL,     -- Desplazamiento en minutos respecto a UTC
  message TEXT NOT NULL,                      -- Mensaje de confort personalizado generado por la IA para la tarde
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Habilitar RLS (Row Level Security) para mayor seguridad
ALTER TABLE alivio.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Conceder permisos de uso al esquema alivio para los roles de la API de Supabase
GRANT USAGE ON SCHEMA alivio TO anon, authenticated, service_role;

-- Conceder permisos sobre la tabla para los roles de lectura y escritura
GRANT ALL ON TABLE alivio.push_subscriptions TO service_role;
GRANT INSERT, SELECT, UPDATE ON TABLE alivio.push_subscriptions TO anon, authenticated;

-- Eliminar políticas previas si ya existen para evitar errores 42710
DROP POLICY IF EXISTS "Permitir insertar suscripciones" ON alivio.push_subscriptions;
DROP POLICY IF EXISTS "Permitir lectura al administrador" ON alivio.push_subscriptions;

-- Crear políticas para permitir inserciones públicas anónimas
CREATE POLICY "Permitir insertar suscripciones" ON alivio.push_subscriptions
  FOR INSERT WITH CHECK (true);

-- Crear políticas para lectura interna
CREATE POLICY "Permitir lectura al administrador" ON alivio.push_subscriptions
  FOR SELECT TO service_role USING (true);
