-- Esquema SQL para la base de datos de Alivio en Supabase
-- Puedes ejecutar esto directamente en el SQL Editor de tu proyecto de Supabase.
-- Es idempotente: se puede volver a correr sobre una base ya creada.

-- Crear el esquema personalizado "alivio" si no existe
CREATE SCHEMA IF NOT EXISTS alivio;

-- ─────────────────────────────────────────────────────────────────────────────
-- Suscripciones a notificaciones push
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS alivio.push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription JSONB NOT NULL,                -- Endpoint y llaves (auth, p256dh) del navegador. Objeto vacío en Android nativo.
  fcm_token TEXT,                             -- Token de Firebase Cloud Messaging. Solo en Android nativo.
  alert_time VARCHAR(5) NOT NULL,             -- Formato "HH:MM" de 24 horas (ej: "17:00")
  timezone_offset INT DEFAULT 0 NOT NULL,     -- Desplazamiento en minutos respecto a UTC
  message TEXT NOT NULL,                      -- Mensaje de confort personalizado generado por la IA para la tarde
  last_sent_at TIMESTAMPTZ,                   -- Último envío efectivo. Base de la deduplicación en cron-push.
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Columnas añadidas después de la creación original de la tabla
ALTER TABLE alivio.push_subscriptions ADD COLUMN IF NOT EXISTS fcm_token TEXT;
ALTER TABLE alivio.push_subscriptions ADD COLUMN IF NOT EXISTS last_sent_at TIMESTAMPTZ;

-- El cron busca por token y el alta deduplica por token: sin índice hace scan completo.
CREATE INDEX IF NOT EXISTS push_subscriptions_fcm_token_idx
  ON alivio.push_subscriptions (fcm_token)
  WHERE fcm_token IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- Permisos
-- ─────────────────────────────────────────────────────────────────────────────
-- Toda la API usa el service role. `anon` y `authenticated` no deben tener ningún
-- permiso sobre esta tabla: contiene endpoints de push y tokens FCM de los usuarios.
ALTER TABLE alivio.push_subscriptions ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA alivio TO service_role;
REVOKE ALL ON SCHEMA alivio FROM anon, authenticated;

GRANT ALL ON TABLE alivio.push_subscriptions TO service_role;
REVOKE ALL ON TABLE alivio.push_subscriptions FROM anon, authenticated;

-- Retirar las políticas heredadas que abrían la tabla al rol anónimo
DROP POLICY IF EXISTS "Permitir insertar suscripciones" ON alivio.push_subscriptions;
DROP POLICY IF EXISTS "Permitir lectura al administrador" ON alivio.push_subscriptions;

-- Sin políticas: con RLS activo y sin grants, solo el service role (que las omite)
-- puede leer o escribir. Es exactamente lo que necesita la API.

-- ─────────────────────────────────────────────────────────────────────────────
-- Evangelio del Día — caché de lecturas (fase 3)
-- ─────────────────────────────────────────────────────────────────────────────
-- Esto es una CACHÉ, no un archivo. El texto litúrgico es de terceros (Evangelizo y
-- Vatican News, con derechos) y se guarda solo para no pegarles una vez por usuario.
-- `/api/readings` purga lo que pasa de 45 días. No conviertas esta tabla en un corpus
-- permanente ni la empaquetes offline sin licencia: ver docs/ethical_ai.md.
CREATE TABLE IF NOT EXISTS alivio.daily_readings (
  reading_date DATE NOT NULL,                 -- Día litúrgico, no la fecha de ingesta
  lang VARCHAR(2) NOT NULL,                   -- 'es' | 'en'
  liturgic_title TEXT,                        -- litugic_t de Evangelizo (sí, con su errata)
  saint TEXT,                                 -- Santo del día; contexto secundario en la UI
  first_reading JSONB,                        -- { ref, label, text }
  psalm JSONB,                                -- Salmo responsorial. Evangelizo siempre lo trae; Vatican News nunca.
  second_reading JSONB,                       -- Solo domingos y solemnidades. NULL el 85 % de los días.
  gospel JSONB,
  papal_comment TEXT,                         -- Comentario del Papa (Vatican News, solo español)
  text_source TEXT NOT NULL,                  -- 'evangelizo' | 'evangelizo+vaticannews'
  vn_applied BOOLEAN DEFAULT FALSE NOT NULL,  -- Falso = la superposición de VN falló y se puede reintentar
  fetched_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  PRIMARY KEY (reading_date, lang)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Evangelio del Día — lote anual de imágenes (fase 3)
-- ─────────────────────────────────────────────────────────────────────────────
-- Una fila por fecha. El prompt se calcula de un banco de plantillas sembrado con el
-- día litúrgico (calapi), nunca con el texto del pasaje: ver el skill de contenido.
CREATE TABLE IF NOT EXISTS alivio.daily_images (
  image_date DATE PRIMARY KEY,
  storage_path TEXT NOT NULL,                 -- Ruta dentro del bucket 'daily-images'
  public_url TEXT NOT NULL,
  prompt TEXT NOT NULL,                       -- El prompt exacto, para poder auditar el lote
  seed BIGINT NOT NULL,                       -- Derivado de la fecha: el lote es reproducible
  season TEXT,                                -- advent | christmas | lent | easter | ordinary
  colour TEXT,                                -- Color litúrgico del día según calapi
  blocked BOOLEAN DEFAULT FALSE NOT NULL,     -- Interruptor por fecha: /api/readings ignora la fila
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- El lote se salta las fechas ya resueltas: sin índice, cada tanda hace scan completo.
CREATE INDEX IF NOT EXISTS daily_images_pending_idx
  ON alivio.daily_images (image_date)
  WHERE blocked = FALSE;

-- Mismo régimen que push_subscriptions: solo el service role.
ALTER TABLE alivio.daily_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE alivio.daily_images ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE alivio.daily_readings TO service_role;
GRANT ALL ON TABLE alivio.daily_images TO service_role;
REVOKE ALL ON TABLE alivio.daily_readings FROM anon, authenticated;
REVOKE ALL ON TABLE alivio.daily_images FROM anon, authenticated;
